### ISSUE TITLE
Mobile search function

### ISSUE THREAD

**Issue by xiezhoubin** [AlxMedia/motioner#3]
If you browse the motioner theme on the mobile phone, the mobile phone input method cannot input content when using search, but it can be on the computer. The version is 1.1.4.

**Comment by AlxMedia** [comment]
Hi, I am aware of this issue - however I haven't found any good solution for it yet.

For now, you need to not use a input in the sidebar. Try putting it in the footer widget or change theme.

I will see if I can add a search button to the mobile header in the next version.

**Comment by xiezhoubin** [comment]
Will&nbsp;the&nbsp;original&nbsp;1.1.3&nbsp;have&nbsp;this&nbsp;problem?


---Original---
From: &quot;Alexander ***@***.***&gt;
Date: Thu, Mar 17, 2022 00:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AlxMedia/motioner] Mobile search function (Issue #3)




 
Hi, I am aware of this issue - however I haven't found any good solution for it yet.
 
For now, you need to not use a input in the sidebar. Try putting it in the footer widget, using the header search or change theme.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlxMedia** [comment]
Yep, same problem in 1.1.3. I am working on a search button in the header for mobile right now.

**Comment by xiezhoubin** [comment]
That's&nbsp;great.&nbsp;I&nbsp;hope&nbsp;it&nbsp;can&nbsp;be&nbsp;done&nbsp;soon.&nbsp;Thank&nbsp;you.&nbsp;By&nbsp;the&nbsp;way,&nbsp;I&nbsp;would&nbsp;like&nbsp;to&nbsp;ask,&nbsp;what&nbsp;is&nbsp;the&nbsp;name&nbsp;of&nbsp;the&nbsp;code&nbsp;highlighting&nbsp;plug-in&nbsp;in&nbsp;the&nbsp;picture,&nbsp;I&nbsp;think&nbsp;it&nbsp;is&nbsp;very&nbsp;nice?


---Original---
From: "Alexander ***@***.***&gt;
Date: Thu, Mar 17, 2022 00:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AlxMedia/motioner] Mobile search function (Issue #3)




 
Yep, same problem in 1.1.3. I am working on a search button in the header for mobile right now.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlxMedia** [comment]
I can't read your message, try writing it on GitHub instead of mail. 

Try version 1.1.5 now. Search added to header for tablet and mobile.

**Comment by xiezhoubin** [comment]
Ok,&nbsp;think&nbsp;you


---Original---
From: &quot;Alexander ***@***.***&gt;
Date: Thu, Mar 17, 2022 01:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AlxMedia/motioner] Mobile search function (Issue #3)




 
I can't read your message, try writing it on GitHub instead of mail.
 
Try version 1.1.5 now. Search added to header for tablet and mobile.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
