### ISSUE TITLE
version 1.1.5 failed to search

### ISSUE THREAD

**Issue by xiezhoubin** [AlxMedia/motioner#4]
1. I tried version 1.1.5, but failed to search on my mobile phone.How to add headers?
2. I would like to ask what is the name of the plug-in with highlighted code in WordPress?
![code](https://user-images.githubusercontent.com/75734559/158657390-5dbfd303-915a-4372-8ef1-6c7076d9061a.png)

**Comment by xiezhoubin** [comment]
I have succeeded. But I hope the search on the mobile phone is displayed at the top of the article.

**Comment by AlxMedia** [comment]
![Image](https://i.imgur.com/GM5YdLi.png)

**Comment by AlxMedia** [comment]
Does it work for you?

**Comment by xiezhoubin** [comment]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/75734559/158660736-ec6de60b-c678-4718-8299-c4995aa93546.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/75734559/158660819-08061e93-2f44-4c7a-83e9-2616972bfc65.png">
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/75734559/158660890-c6c12762-e213-4c60-900e-f7d4bc426b5e.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/75734559/158660962-f1dfe244-6f78-4723-994e-6f864157d234.png">
The search is still not displayed on the top. Did you not upload the latest theme?

**Comment by AlxMedia** [comment]
I did upload the latest. Try force-refreshing the page by pressing CTRL+F5. Clear/purge cache.

**Comment by xiezhoubin** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/75734559/158661686-541c786c-480b-4635-93b7-7866e20f802d.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/75734559/158661734-533ba83a-356d-45cb-a73a-2dd1f8dc6647.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/75734559/158661766-d2bce72d-5d0a-4237-9b83-7df44718893d.png">
I checked the example of your official website, and there is no search

**Comment by xiezhoubin** [comment]
Successful, thank you very much!

**Comment by AlxMedia** [comment]
Great!
