### ISSUE TITLE
Modify the font size of the navigation bar menu

### ISSUE THREAD

**Issue by xiezhoubin** [AlxMedia/motioner#5]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/75734559/158665077-fef13a68-1f24-4fe0-8a09-c8b1e6d1ff3e.png">
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/75734559/158665123-4a1d6591-87f1-471a-8589-bde5889ab487.png">
If I want to change the font size of the navigation bar menu, what should I do? I see a CSS about menu here, but I don't know how to modify it.

**Comment by AlxMedia** [comment]
Go to Customize > Additional CSS and add:
``
.nav-menu:not(.mobile) { font-size: 18px; }
``
16px is default.

**Comment by xiezhoubin** [comment]
succeed. But it seems that 18px is more appropriate. A little bigger will disrupt the layout. Ha ha

**Comment by AlxMedia** [comment]
Glad you got it to work :-)
